name: se7en
description: Se7en ecommerce app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0

  # Firebase
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0
  firebase_storage: ^12.4.10
  cached_network_image: ^3.4.1
  firebase_messaging: ^15.1.2  
  firebase_crashlytics: ^4.1.3
  # (أضف أي باكدجات أخرى تستخدمها لاحقًا)
  intl: ^0.20.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  flutter_svg: ^2.0.9
  device_info_plus: ^10.1.0   # لاكتشاف قوة/قدم الجهاز
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/se7en_logo.png
    - assets/icons/riyal.svg
    - assets/textures/noise.png
    - assets/cats/
    
